table vw_ActualVsBudget
	lineageTag: 524a63d2-fc7e-475e-b91b-8b1b4b5af93c

	column CompanyName
		dataType: string
		lineageTag: 45ceaf9f-a3d1-43ba-aea2-553c7b002fc2
		summarizeBy: none
		sourceColumn: CompanyName

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: a1aa3098-25d7-4747-9fc6-ccb3ae4ebda8
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b3c86d06-7a02-416b-b773-172936fb672c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 66c7e47d-0341-475e-aebd-c2b2cf4bf691
		summarizeBy: sum
		sourceColumn: QuarterNumber

		annotation SummarizationSetBy = Automatic

	column IndicatorCode
		dataType: string
		lineageTag: 9a95fcdd-0f00-45a4-abcc-6e318655bd4f
		summarizeBy: none
		sourceColumn: IndicatorCode

		annotation SummarizationSetBy = Automatic

	column IndicatorName
		dataType: string
		lineageTag: 7d4edbd4-5d0a-4967-9e6c-684df9d8fa04
		summarizeBy: none
		sourceColumn: IndicatorName

		annotation SummarizationSetBy = Automatic

	column IndicatorSortOrder
		dataType: int64
		formatString: 0
		lineageTag: 408acfd2-1090-429e-a24a-1e418d0965fc
		summarizeBy: sum
		sourceColumn: IndicatorSortOrder

		annotation SummarizationSetBy = Automatic

	column ActualAmount
		dataType: double
		lineageTag: 0f367c64-6890-4039-87a9-fcf100bf55e7
		summarizeBy: sum
		sourceColumn: ActualAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BudgetAmount
		dataType: double
		lineageTag: 012fa30e-33cb-4b74-b1a3-d10a5be28291
		summarizeBy: sum
		sourceColumn: BudgetAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Variance
		dataType: double
		lineageTag: b2b892ac-4a8a-417b-8503-91c147001c61
		summarizeBy: sum
		sourceColumn: Variance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VariancePercent
		dataType: double
		lineageTag: 4bca78b0-61ce-4b0f-a11e-10a6fbe71afb
		summarizeBy: sum
		sourceColumn: VariancePercent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PeriodKey
		dataType: int64
		formatString: 0
		lineageTag: b8bdd017-69b3-4fbb-b503-c0b850d48d3b
		summarizeBy: none
		sourceColumn: PeriodKey

		annotation SummarizationSetBy = Automatic

	partition vw_ActualVsBudget = m
		mode: import
		source =
				let
				    Source = Sql.Database(pServerName, pDatabaseName),
				    dbo_vw_ActualVsBudget = Source{[Schema="dbo",Item="vw_ActualVsBudget"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_vw_ActualVsBudget,{{"Year", Int64.Type}, {"QuarterNumber", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

