table vw_DebtAnalysis
	lineageTag: 84436fe3-273b-4bb6-9b09-04cb35ad60d1

	column CompanyName
		dataType: string
		lineageTag: 9803f289-ac1a-4fae-9513-d1ea1ff1bfd3
		summarizeBy: none
		sourceColumn: CompanyName

		annotation SummarizationSetBy = Automatic

	column PeriodKey
		dataType: int64
		formatString: 0
		lineageTag: fcc5c1f1-2546-4263-8c17-0eab6bb1e6f7
		summarizeBy: none
		sourceColumn: PeriodKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 67053cb7-6888-47a2-a69d-2b60050352ea
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b379c17e-9f9b-4eb2-aca6-d185fc31b512
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: a806bff1-6121-47fd-9148-4123069f2d11
		summarizeBy: sum
		sourceColumn: QuarterNumber

		annotation SummarizationSetBy = Automatic

	column DebtMetricId
		dataType: int64
		formatString: 0
		lineageTag: 0f261f17-cf92-4cda-9e94-b3d9c327afaf
		summarizeBy: count
		sourceColumn: DebtMetricId

		annotation SummarizationSetBy = Automatic

	column DebtMetricName
		dataType: string
		lineageTag: 50867cce-7f82-49e0-b21e-2708c942cfea
		summarizeBy: none
		sourceColumn: DebtMetricName

		annotation SummarizationSetBy = Automatic

	column ActualValue
		dataType: double
		lineageTag: d829dccc-128a-4030-a7aa-e6a3fd0cc7d4
		summarizeBy: sum
		sourceColumn: ActualValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BudgetValue
		dataType: double
		lineageTag: 7c0a2a00-156f-4297-8b64-8b1f544bd329
		summarizeBy: sum
		sourceColumn: BudgetValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Variance
		dataType: double
		lineageTag: 7f22e9fd-a381-4e23-976a-1cfae7f244e2
		summarizeBy: sum
		sourceColumn: Variance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VariancePercent
		dataType: double
		lineageTag: 7f348803-58b2-4c53-b11d-6f24bbd8902a
		summarizeBy: sum
		sourceColumn: VariancePercent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition vw_DebtAnalysis = m
		mode: import
		source =
				let
				    Source = Sql.Database(pServerName, pDatabaseName),
				    dbo_vw_DebtAnalysis = Source{[Schema="dbo",Item="vw_DebtAnalysis"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_vw_DebtAnalysis,{{"Year", Int64.Type}, {"QuarterNumber", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

